### ISSUE TITLE
 Missing Documentation: Adding Inline Images to Emails

### ISSUE THREAD

**Issue by jltrevizon** [resendlabs/resend-python#115]
Hi there,

I'm trying to add inline images to emails sent using the Resend SDK, but I can't find any information on how to do this in the documentation.

Could you please provide guidance on how to embed images directly into the email body using the SDK?

Specifically, I'm looking for information on:

    The correct method to use for adding inline images.

    The required format for the image file.

    Any specific parameters or options related to inline images.

Thank you for your help!

**Comment by drish** [comment]
Hey @jltrevizon thanks for opening the issue. Inline uploads are not supported by the Resend API yet, a possible workaround is to host your images on some external url and link them on your email image tags, something like: `<img src="https://external/img.png>"`

lmk if that works for you ?

**Comment by drish** [comment]
closing this issue for now, let us know if you have any other issues
