### ISSUE TITLE
Error Sending Emails: ApplicationError and PicklingError

### ISSUE THREAD

**Issue by brenonsc** [resendlabs/resend-python#117]
I am experiencing an issue with the resend service, where several email sends have failed around 10:00 AM (GMT -03:00). The following errors were encountered in the console:

```
Exception     
<MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: ApplicationError(\'column "sent_at" of relation "emails" does not exist\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'resend.exceptions.ApplicationError\'>: it\'s not the same object as resend.exceptions.ApplicationError")''.>

Traceback (most recent call last):
  File "/home/contabee/contabee/lib/lib/python3.7/site-packages/billiard/pool.py", line 366, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/home/contabee/contabee/lib/lib/python3.7/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/contabee/contabee/lib/lib/python3.7/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: ApplicationError(\'column "sent_at" of relation "emails" does not exist\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'resend.exceptions.ApplicationError\'>: it\'s not the same object as resend.exceptions.ApplicationError")''.
```

**Details:**
Timeframe: The errors occurred around 10:00 AM (GMT -03:00).
Error Pattern: There doesn't seem to be an observable pattern in the occurrences of these errors.
Environment: Python 3.7

**Request for Support:**
I would like to know if this issue is due to a server-side problem, a potential bug in the resend platform, or if the traceback indicates any issues in my code. Any guidance or support you could provide would be greatly appreciated.

**Comment by brenonsc** [comment]
**Additional info:**
The emails that encounter these errors are not recorded in the service logs and are not displayed as failures, making it difficult to track these incidents.

**Comment by drish** [comment]
hey @brenonsc, yeah that looks like the resend API had a small hiccup and the responses were not what the SDK expected to be, I will ask the team to investigate that timeframe further, in the meantime would you know which version of the SDK you were in when those errors happened ? 
Last week I released: [v2.3.0](https://github.com/resend/resend-python/releases/tag/v2.3.0) which should gracefully handle non json responses from the API.

**Comment by brenonsc** [comment]
The first one: 2024-07-30 12:59:09.261 UTC
The last one: 2024-07-30 13:11:39.418 UTC

**Comment by felipevolpone** [comment]
Hey @brenonsc, a bad deployment lead to this problem and disrupted some APIs. As @drish pointed, the new version of the python sdk has a better error handling when there are issues with the API
