### ISSUE TITLE
Feature Request: Add Webhook Support for Domain Management

### ISSUE THREAD

**Issue by brenonsc** [resendlabs/resend-python#123]
I would like to request a new feature to add webhook support for domain management, specifically to receive real-time notifications for domain verification status and other possible domain information. 

Is this something that could be considered for future releases?

Thank you for your hard work and consideration!

**Comment by briankerr** [comment]
@brenonsc Thank you for the feedback, Breno! What other domain related events would you like to receive via webhooks? I'll create a feature request for you.

**Comment by brenonsc** [comment]
@briankerr thank you for considering my feedback! I would appreciate receiving updates primarily about the domain status and maybe any changes in DNS records through webhooks.

**Comment by zenorocha** [comment]
@brenonsc we've added webhooks for domain management based on your feedback.

See documentation here: https://resend.com/docs/dashboard/webhooks/event-types#domain-created

Let us know if you have any feedback or suggestions.
