### ISSUE TITLE
make pinning of requests less restrictive due to urllib3 debacle

### ISSUE THREAD

**Issue by djstein** [resendlabs/resend-python#28]
hey all,

as you may know urllib3's breaking change to version 2 is causing widespread issues.
many packages have upgraded to support urllib3 2+, or at least the latest security patches at 1.26.X.

currently an issue with requests: https://github.com/psf/requests/issues/6443 for requests version 2.23.0 is resulting in only installing `urllib3` at 1.25 or lower.

I encountered this when trying to install the `sentry-sdk` within a new Django project.
notice that the sentry-sdk install_requires for Python is at: https://github.com/getsentry/sentry-python/blob/master/setup.py#L43

if the pinning for `resend` is changed to say `requests>=2.29.0`  this issue should be resolved. where 2.29.0 supports `requests 2.29.0 depends on urllib3<1.27 and >=1.21.1` and any new versions can be supported

**Comment by drish** [comment]
thanks for reporting @djstein , will look into it

**Comment by lharries** [comment]
Running into the same issue here

**Comment by drish** [comment]
@djstein @lharries  just released [v0.5.1](https://github.com/resendlabs/resend-python/releases/tag/v0.5.1) which points to requests 2.31.0. Lmk if you're still seeing any issues ?
