### ISSUE TITLE
Example code in README not working

### ISSUE THREAD

**Issue by bitzeno** [resendlabs/resend-python#56]
I'm on Python3.10, macOS 12. I just installed resend package in a fresh virtual environment and ran the example code in the README. 

I'm getting this error

`AttributeError: partially initialized module 'resend' has no attribute 'Emails' (most likely due to a circular import)`

**Comment by drish** [comment]
hey @justchaying, thanks for reporting your issue. Is the file you created to run the example named `resend.py` by any chance ? That could conflict with the actual pip installed package and give you that error.
If that's the case, try renaming that to anything else and run again, lmk if you run into any other issues

**Comment by bitzeno** [comment]
That fixed it. Thanks! Appreciate your help.

**Comment by sudeephazra** [comment]
It looks like the SDK also does not like if the file is named "email.py" 😆
