### ISSUE TITLE
Better support for type hinting

### ISSUE THREAD

**Issue by drish** [resendlabs/resend-python#70]
- [x] MyPy in CI (https://github.com/resend/resend-python/pull/71)
- [x] Tox command for mypy (https://github.com/resend/resend-python/pull/71)
- [x] Annotate ApiKeys component (https://github.com/resend/resend-python/pull/71)
- [x] Annotate Domains component (https://github.com/resend/resend-python/pull/71)
- [x] Annotate Emails component (https://github.com/resend/resend-python/pull/71)
- [x] Annotate Batch component (https://github.com/resend/resend-python/pull/71)
- [x] Annotate Contacts component (https://github.com/resend/resend-python/pull/71)
- [x] Annotate Audiences component (https://github.com/resend/resend-python/pull/71)
- [x] Update all examples under the /examples folder(https://github.com/resend/resend-python/pull/76)
- [x] Update Readme examples

**Comment by jermatic** [comment]
yeah, was about to open an issue for this. The lack of type hinting means I cant even use this client :/ goina have to write my own code as needed until there is full proper type hinting

**Comment by drish** [comment]
https://github.com/resend/resend-python/releases/tag/v1.0.0
