### ISSUE TITLE
Wrong type for Batch response

### ISSUE THREAD

**Issue by yehuda-margolis** [resendlabs/resend-python#72]
https://github.com/resend/resend-python/blob/544b4518ab65b2976f7b3a54cfdbf221a76e2f3d/resend/batch.py#L14

Seems like the typing here is wrong...
The response is actually in this format -> 
```
{
  "data": [
    {
      "id": "ae2014de-c168-4c61-8267-70d2662a1ce1"
    },
    {
      "id": "faccb7a5-8a28-4e9a-ac64-8da1cc3bc1cb"
    }
  ]
}
```
should be Dict[str, Dict]

**Comment by drish** [comment]
@yehuda-margolis thanks for opening the ticket, we're doing an entire type hinting revamp for the next sdk major release, which should be live soon: https://github.com/resend/resend-python/pull/71

**Comment by drish** [comment]
[v1.0.0](https://github.com/resend/resend-python/releases/tag/v1.0.0) has been released
