### ISSUE TITLE
Webhook Listener Fails to Distinguish Emails Sent from Different Domains

### ISSUE THREAD

**Issue by brenonsc** [resendlabs/resend-python#83]
Currently, the handling of webhooks does not adequately differentiate between emails sent from distinct domains when utilizing the same account. This results in webhooks intended for one domain continuing to listen to email sends from other domains associated with the same account.

**Potential Solution:**
Implement a mechanism to ensure that webhooks are bound strictly to the domain they are configured for, thereby preventing cross-domain triggering.

**Comment by bukinoshita** [comment]
> Currently, the handling of webhooks does not adequately differentiate between emails sent from distinct domains when utilizing the same account. This results in webhooks intended for one domain continuing to listen to email sends from other domains associated with the same account.
> 
> **Potential Solution:** Implement a mechanism to ensure that webhooks are bound strictly to the domain they are configured for, thereby preventing cross-domain triggering.

Great suggestion, that's definitely a valid feature.
In the meantime is it possible to handle which webhooks you receive by looking at the `from`. I just opened a ticket as a feature request for this.
