### ISSUE TITLE
Can you guys bump requests to `requests==2.32.0`?

### ISSUE THREAD

**Issue by kevinlu1248** [resendlabs/resend-python#97]
Dependabot says 2.31.0 has some vulnerability and resend isn't letting us bump the requests version: https://github.com/sweepai/sweep/actions/runs/9217012429/job/25358304944.

**Comment by drish** [comment]
yeah thanks for reporting @kevinlu1248 , we'll be releasing `v1.2.0` today which will make requests >= 2.31

**Comment by drish** [comment]
@kevinlu1248 fyi: the latest release points to request >= 2.31
